export const BACK_W = require('$image/balance/back.svg')
export const ELLIPSIS_W = require('$image/balance/ellipsis.svg')
// export const BACK_B = require('$image/accountNew/back_b.png')
// export const ELLIPSIS_B = require('$image/accountNew/elesips_b.png')
export const ACCOUNT_BG = require('$image/accountNew/account_bg.png')
export const RIGHT_ARROW = require('$image/loan/getmore.svg')
export const ELLIPSIS_L = require('$image/accountNew/elesips.svg')
export const BG = require('$image/accountNew/bg.svg')

export const EYE_SHOW_W = require('$image/accountNew/eyeShowW.svg')
export const EYE_CLOSE_W = require('$image/accountNew/eyeCloseW.svg')
export const EYE_SHOW = require('$image/accountNew/eyeShow.svg')
export const EYE_CLOSE = require('$image/accountNew/eyeClose.svg')
export const WDDK = require('$image/home/my/wddk.svg')